### ISSUE TITLE
MSpawns

### ISSUE THREAD

**Issue by EdwardHamHam** [poggit-orphanage/office#1]
MSpawns was a plugin that allowed you to make multiple different spawn points, set a server hub, and name each spawn point by making an alias, thus giving it it's own command (i. e. you could make /pvp teleport you to the spawn for PvP). It was a very useful plugin, which also came with configurable chat messages. The plugin's Github repository can be found [here](https://github.com/EvolSoft/MSpawns/blob/master/resources/config.yml).
The plugin has not been updated in awhile, and I thought it would benefit a lot of people for it to be updated.

**Comment by SOF3** [comment]
The author already submitted it. https://poggit.pmmp.io/p/MSpawns
