### ISSUE TITLE
Request of PureEntitiesX being re-revived

### ISSUE THREAD

**Issue by PermissionError** [poggit-orphanage/office#10]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:
Please add the PureEntities plugin to a poggit release and update to newest version of API. It really breaks the game to not have mobs.

#### Plugin Name

PureEntitiesX

#### Link to GitHub repo

https://github.com/RevivalPMMP/PureEntitiesX

#### Is it in the pre-Alpha_1.4 format?

No, it's not.

#### Does the plugin work in the latest PocketMine version?

Nope...

#### Does the plugin depend on other plugins? Are they released on Poggit?

No.

#### Are the main authors still active?

Probably not.

**Comment by SOF3** [comment]
https://poggit.pmmp.io/p/PureEntitiesX

**Comment by SOF3** [comment]
@Sandertv According to the auto-detected author list, you were a main collaborator of the repo. Any opinions?

**Comment by Sandertv** [comment]
I started it as a fun project with @Magicode1, but it got so many contributions that I didn't need to help anymore and Magicode left, so I'm not really in the mind to work on it again. @jasonwynn10 is also working on it, perhaps ask him.

**Comment by jasonw4331** [comment]
The main developer @kniffo80 has left the scene, so continuing work has been hard due to the fact that we, the other developers, don't know what he was planning to do with it. Feel free to take on the job, but I believe it would be easier to start from scratch and just put entities into PocketMine itself.

**Comment by SOF3** [comment]
So nobody from PureEntitiesX wants to continue the work anyway?

**Comment by jasonw4331** [comment]
I've attempted it a few times, but AI isn't my strong suit

**Comment by PermissionError** [comment]
:-) looks like the project has some hope!

**Comment by Awzaw** [comment]
It would be easier if https://github.com/pmmp/PocketMine-MP/blob/7d3fca83f090f181bb1096e59fa48b59b987f5df/src/pocketmine/tile/Spawnable.php#L80 wasn't final. @SOF3 if nobody is doing anything with it, should we add it to poggit-orphanage?

**Comment by Awzaw** [comment]
You can test it out [here](https://poggit.pmmp.io/ci/poggit-orphanage/PureEntitiesX/~). Should this be released by Poggit-Orphanage, or PR'd to the RevivalPMMP repo?

**Comment by PermissionError** [comment]
O.M.G. You people are awesome.

**Comment by PermissionError** [comment]
[13:32:25] [Server thread/INFO]: Loading PureEntitiesX v0.2.3
[13:32:25] [Server thread/CRITICAL]: ErrorException: "Declaration of revivalpmmp\pureentities\entity\monster\WalkingMonster::onUpdate(int $currentTick): bool should be compatible with pocketmine\entity\Entity::onUpdate($currentTick)" (EXCEPTION) in "PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster" at line 42
[13:32:25] [Server thread/CRITICAL]: Could not load plugin 'PureEntitiesX'

Well, looks like pmmp's not happy with it

**Comment by PermissionError** [comment]
Sorry guys for giving you more trouble by requesting a plugin. I personally have no knowledge in php programming so I can do nothing to help you, even though I really want to.
TO-DO LIST:
Start on php

**Comment by jasonw4331** [comment]
@kniffo80 decided he wanted the plugin to support multiple PocketMine versions, so multiple versions were taken into account for various things. Much of the plugin works, but your console will definitely be spammed with errors by the time your decide to turn off your server 😋

**Comment by PermissionError** [comment]
No, the plugin doesn't even work. It won't enable itself on API 3.0.0 ALPHA 7 @jasonwynn10

**Comment by PermissionError** [comment]
BTW everyone that work at orphan, you need to update the description for [ItemCase](https://poggit.pmmp.io/p/ItemCase/1.1.0-dev1) on poggit to support API 3.0.0 ALPHA7, or people that don't read plugin.yml will just skip the plugin and miss the goods.

**Comment by PermissionError** [comment]
Guys I fixed it, being the noob at php I am, went into every file and deleted the int declare infront of $currentTick and $tickDiff, fixed. Tested. Mobs do stray around endlessly but hey, they WORK!

**Comment by PermissionError** [comment]
Did a poggit repo [here](https://poggit.pmmp.io/ci/TBNRShadowDev/PureEntitiesX/~)

**Comment by Sandertv** [comment]
That int type hint _should_  be there for the latest PocketMine version.

**Comment by PermissionError** [comment]
Weird thing is, it _doesn't_ work for latest PMMP

**Comment by jasonw4331** [comment]
@TBNRShadowDev If it only works without the typehints, then you aren't using pmmp's latest version

**Comment by PermissionError** [comment]
Isn’t ALPHA7 the latest???

**Comment by Awzaw** [comment]
Works for me, what exact version are you using? ALPHA7 is liable to change, and break everything, at any time... and there are two branches on Poggit, one for latest master branch, another for mcpe1.2 branch.

**Comment by Awzaw** [comment]
I've merged damage-reduction, and updated for the latest breaking changes on alpha7 (master branch for MCPE 1.1). Let me know if you still have problems, and please bear in mind that alpha7 is not yet tagged, so I may have to update again tomorrow for the next version of alpha7, which may break backward compatibility again...

**Comment by PermissionError** [comment]
Guys I'm sincerely sorry about my stupidity. I downloaded the latest build from poggit and it worked. Sorry Guys!

**Comment by robske110** [comment]
due to the plugin on the (semi)-original repo now being under active development again, this can be closed until further notice
