### ISSUE TITLE
MagicTelePortal

### ISSUE THREAD

**Issue by Arctiblaine** [poggit-orphanage/office#11]
#### Plugin Name
MagicTelePortal

#### Link to GitHub repo
https://github.com/Muirfield/MagicTelePortal

#### Link to PocketMine Forums release
http://forums.pocketmine.net/plugins/magicteleportal.1146/

#### Is it in the pre-Alpha_1.4 format?
No.

#### Does the plugin work in the latest PocketMine version?
It used to work until the ALPHA-7 update. Now it doesn't work.

#### Does the plugin depend on other plugins? Are they released on Poggit?
No dependency needed.

#### Are the main authors still active?
They're the one that did WorldProtect, and that plugin was requested on here. So, yes. Muirfield, If I spelled it correctly, is the author's name?

**Comment by Awzaw** [comment]
Fixed, and added to Poggit: https://poggit.pmmp.io/p/MagicTelePortal

**Comment by Arctiblaine** [comment]
Thank you! Much appreciated.
