### ISSUE TITLE
ClearLagg

### ISSUE THREAD

**Issue by AffanStarPure** [poggit-orphanage/office#14]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name
ClearLagg

#### Link to GitHub repo
https://github.com/LegendOfMCPE/ClearLagg

#### Link to PocketMine Forums release
No

#### Is it in the pre-Alpha_1.4 format?
Not Work On 3.0.0 ALPHA 7-9 PocketMine MP

#### Does the plugin work in the latest PocketMine version?
i try update not work

#### Does the plugin depend on other plugins? Are they released on Poggit?
idk sorry

#### Are the main authors still active?
No Is Too Old

**Comment by SOF3** [comment]
If you consult the [contributor graph](https://github.com/LegendOfMCPE/ClearLagg/graphs/contributors), @Falkirks was the main author, and apparently active.

But @Falkirks I suppose you have no intention in updating it, right? Would you agree if I just transfer the repo to poggit-orphanage, shall this request be approved?

**Comment by Sandertv** [comment]
Alternatively I could update it in the LegendsOfMCPE repository as well, I'm cool with that.

**Comment by SOF3** [comment]
@Sandertv You've been added :)
