### ISSUE TITLE
Rankup

### ISSUE THREAD

**Issue by AffanStarPure** [poggit-orphanage/office#15]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

RankUp

#### Link to GitHub repo

https://github.com/Falkirks/RankUp

#### Link to PocketMine Forums release

http://forums.pocketmine.net/plugins/rankup.830/

#### Was it released before mid-2014?

is dont work on 3.0.0 ALPHA 7-9 PocketMine-MP

#### Does the plugin work in the latest PocketMine version?

i have been updated getting error 

#### Does the plugin depend on other plugins? Are they released on Poggit?

Yes But Old Alpha Before update 3.0.0 Alpha 7-9

#### Are the main authors still active?

 maybe is last time like 5-7 month ago now no more update to 3.0.0 Alpha 7-9

#### Are there any forks that have updated the plugin to the latest PocketMine version?

No I dont have it sorry

**Comment by EdwardHamHam** [comment]
Your answers don't make sense.

**Comment by SOF3** [comment]
@Falkirks

**Comment by falkirks** [comment]
Uhhhh...can you post the error you are getting over at https://github.com/Falkirks/RankUp/issues/38 ? Your issue received no response because you did not specify the error that occurred.

**Comment by AffanStarPure** [comment]
@Falkirks if i make issue you don't reply update 3.0.0 ALPHA 8-9 pls it we need new one

**Comment by SOF3** [comment]
Since the original author is active, I'm closing this issue as "claimed by parent". Please continue your discussion back in your original issue Falkirks/RankUp#38.
