### ISSUE TITLE
iSoftCrates

### ISSUE THREAD

**Issue by timbersquirrel** [poggit-orphanage/office#16]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

iSoftCrates

#### Link to GitHub repo

https://github.com/AndreySK4/iSoftCrates

#### Link to PocketMine Forums release

https://imgcl.co/plugins/isoftcrates.726/

#### Was it released before mid-2014?

released back in febuary 2017

#### Does the plugin work in the latest PocketMine version?

 
It crashes my server

#### Are the main authors still active?

Yes but he discontinued this plugin

**Comment by Thunder33345** [comment]
please note that imgcl.co link is NOT a valid link to pocketmine forums release
incase you are confused
only links starting with forums.pocketmine.net is a valid link

**Comment by SOF3** [comment]
The same. I just want to know how well-received the plugin is, and maybe some description.
