### ISSUE TITLE
question on AdvancedKits custom enchants

### ISSUE THREAD

**Issue by timbersquirrel** [poggit-orphanage/office#17]
I cant get custom enchants on my kits... i am using pce and for the idem id i do 276:0:1:TestName:sharpness:1:blind:1
it wont let me use the kit i am confused of the format for custom enchants

**Comment by Awzaw** [comment]
That should be correct, assuming you have correctly formatted the yaml. No errors during startup or when you ask for a kit?

**Comment by timbersquirrel** [comment]
works now lol thanks for youre time

**Comment by timbersquirrel** [comment]
closing issue...
