### ISSUE TITLE
AutoCommand/AutoBroadcast

### ISSUE THREAD

**Issue by SyntaxDragon** [poggit-orphanage/office#2]
Do commands by console every <insert time> or broadcast

**Comment by SOF3** [comment]
Poggit orphanage is for updating outdated and unattended plugins, not for plugin requests. Please point to the source repo if such plugin existed.

**Comment by SyntaxDragon** [comment]
https://github.com/dutok/SimpleMessages
Crashes and have bugs

**Comment by SOF3** [comment]
Looks too simple... Pointless to "update" such a simple plugin. Maybe make it a new plugin request instead?
