### ISSUE TITLE
ChestShop needs some fixes

### ISSUE THREAD

**Issue by asyncthreading** [poggit-orphanage/office#20]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

ChestShop

#### Link to GitHub repo

https://github.com/Muqsit/ChestShop

#### Was it released before mid-2014?

No

#### Does the plugin work in the latest PocketMine version?

IT doesnt work at all, it needs some little fixes

#### Does the plugin depend on other plugins? Are they released on Poggit?

https://github.com/onebone/EconomyS , yes, IT is on poggit

#### Are the main authors still active?

Not really.

#### Are there any forks that have updated the plugin to the latest PocketMine version?

No

**Comment by Awzaw** [comment]
@Muqsit is active, did you contact him already?

**Comment by asyncthreading** [comment]
He sayd that he is working on his servers and he has no time.

**Comment by JackNoordhuis** [comment]
The plugin has been updated to ALPHA-10 at the [original repo](https://github.com/Muqsit/ChestShop). If the plugin becomes inactive again feel free to bump this issue.
