### ISSUE TITLE
How to give a kit to a player for 1 time use (Advanced Kits)

### ISSUE THREAD

**Issue by timbersquirrel** [poggit-orphanage/office#22]
I tried setting player permission for use of the kit but i need him to be able to buy the kit from shop but not be able to use it infinite amount of times. Cooldown wont work because they must be able to buy it multiple times with out the cooldown getting in the way

**Comment by Awzaw** [comment]
This isn't entirely clear: 

> not be able to use it infinite amount of times

Can you elaborate?

**Comment by timbersquirrel** [comment]
Someone pays 5$ on buycraft to get a kit (Not a rank.) then the player logs onto the server and types /kit {name}
Then he will be given the kit. If he types /kit {kitname} the kit will not be given again.
If he buys the kit again on the buycraft, the same process will repeat. 
I do NOT know how to make this work :/

**Comment by Thunder33345** [comment]
you need something to revoke the perm, said when the kit is used, run command remove perm to use said kit
and when people pays, you give them a perm to use the kit, kinda hacky setup tho

**Comment by Awzaw** [comment]
Maybe it would be easier to ensure players don't have permission for certain kits, and add the possibility for console /plugins to give kits to online players (`/kit <player> <kitname>`)? Then you could configure buycraft to run the kit command for that player.

**Comment by timbersquirrel** [comment]
Thanks for the help closing issue

**Comment by Awzaw** [comment]
I'll add that to AdvancedKits if you like, or if you already did, feel free to make a PR
