### ISSUE TITLE
Farms

### ISSUE THREAD

**Issue by Haxley** [poggit-orphanage/office#26]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

Farms

#### Link to GitHub repo

https://github.com/organization/Farms/issues

#### Link to PocketMine Forums release

http://forums.pocketmine.net/plugins/farms.789/

#### Was it released before mid-2014?

Not pre mid-2014 or alpha_1.2 release.
Forums Release: Alpha_1.4.1
Github Release: Alpha_2.0.0
Poggit Dev Release: 3.0.0 Alpha_6

#### Does the plugin work in the latest PocketMine version?

No, plugin will not enable even with All API Loader

#### Does the plugin depend on other plugins? Are they released on Poggit?

No

#### Are the main authors still active?

As far as I know, the main authors are not active. 

#### Are there any forks that have updated the plugin to the latest PocketMine version?

No forks have been updated past alpha 6, ~5 months ago. 

#### Why do you want us to update this plugin?

I want this plugin to be updated because Still Water blocks currently flow in PocketMine. Because of this, Water is banned on many servers because of how easily it can be used to grief. This then breaks farming, unless you're able to build your farm on a lake or something. I want this plugin updated so that farming can be done without the need for flowing water.

**Comment by robske110** [comment]
There's a small issue: The license is a weird license in a language I don't understand, and also seems to be a self-made license. We could fork the plugin at a earlier point in time where the license still was `GNU AFFERO GENERAL PUBLIC`. This would require some work to be re-done without copying.

**Comment by Thunder33345** [comment]
the license apparently say something about begin noncommercial

**Comment by SOF3** [comment]
Rejected due to license difficulties.
