### ISSUE TITLE
SkyWars

### ISSUE THREAD

**Issue by SlothyOne** [poggit-orphanage/office#30]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

SkyWars-PocketMine

#### Link to GitHub repo

https://github.com/svilex/SkyWars-PocketMine

#### Was it released before mid-2014?

No.

#### Does the plugin work in the latest PocketMine version?

No.

#### Does the plugin depend on other plugins? Are they released on Poggit?

No.

#### Are the main authors still active?

Yes.

#### Are there any forks that have updated the plugin to the latest PocketMine version?

No.

**Comment by Muqsit** [comment]
I am working on updating this plugin (see commit: https://github.com/Muqsit/SkyWars-PocketMine/commit/3ae952f0f4c3deff081b0cf7400052e09c3af2a2, repo: https://github.com/Muqsit/SkyWars-PocketMine).

The only tests I've made is by creating a skywars game, creating a skywars sign, tapping the sign to join the game, checking whether chests reload and completing the game. There definitely is a lot more to be done, I've prioritized sanity over completion for now (yes, this plugin is annoyingly coded).

But I may not be able to support this for long. I will support it for some weeks (or months if I get enough time) and then transfer the ownership to `poggit-orphanage`.

**Comment by SlothyOne** [comment]
Cheers Muqsit, thanks for going through so much trouble to update it! Much appreciated :-)

**Comment by AirLinesCraft** [comment]
Plugin abandoned, can anyone revive it?

**Comment by SOF3** [comment]
I do not see the need to adopt this plugin, as there are already two SkyWars plugins available on Poggit. Please comment for reopen if you find anything missing in the existing SkyWars plugins that can be found in the requested plugin.
