### ISSUE TITLE
Respond here.

### ISSUE THREAD

**Issue by BrokenItZAndrei100** [poggit-orphanage/office#35]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name
 ZMusicBox

#### Link to GitHub repo
 https://github.com/BrokenItZAndrei100/ZMusicBox/

#### Was it released before mid-2014?
 It's not , is released on Mid 2018.

#### Does the plugin work in the latest PocketMine version?

 Yes it work with latest.

#### Are there any forks that have updated the plugin to the latest PocketMine version?
 https://github.com/BrokenItZAndrei100/ZMusicBox/

**Comment by dktapps** [comment]
You could ask the owner to release it on Poggit instead of trying to claim it as your own. Your fork adds nothing of value.

**Comment by SOF3** [comment]
According to GitHub, the original author is not inactive (Still has activity in December 2018). Poggit Orphanage is only for orphans.
