### ISSUE TITLE
CmdSnooper

### ISSUE THREAD

**Issue by ggomezz** [poggit-orphanage/office#36]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name
CmdSnooper

#### Link to GitHub repo
https://github.com/HotshotHD/CmdSnooper

#### Link to PocketMine Forums release
N/A

#### Was it released before mid-2014?
No. 2016.

#### Does the plugin work in the latest PocketMine version?
My updated version works with the latest API. Theirs does not.
3.6.5

#### Does the plugin depend on other plugins? Are they released on Poggit?
No dependencies.

#### Are the main authors still active?
No.

#### Are there any forks that have updated the plugin to the latest PocketMine version?
Mine. https://github.com/ggomezz/CmdSnooper

**Comment by SOF3** [comment]
The original repo did not have a license. I am not sure if we are allowed to do this.

**Comment by SOF3** [comment]
In addition, as of recent PMMP updates, you can use CommandEvent instead (and it really shouldn't use PlayerCommandPreprocessEvent). I would say that it's easier to make a new one than to clone the old one. This is a simple plugin, after all.
