### ISSUE TITLE
Murder by TheNewHEROBRINEX/Murder

### ISSUE THREAD

**Issue by ghost** [poggit-orphanage/office#37]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

Murder

#### Link to GitHub repo

https://github.com/TheNewHEROBRINEX/Murder

#### Was it released before mid-2014?

No

#### Does the plugin work in the latest PocketMine version?

No, it’s function for 3.0.0- ALPHA11 (please update to latest)

#### Does the plugin depend on other plugins? Are they released on Poggit?

No I don’t think so

#### Are the main authors still active?

No they didn’t do anything since beginning of 2018

#### Are there any forks that have updated the plugin to the latest PocketMine version?
No

Please awnser as soon as u can

**Comment by SOF3** [comment]
Since this plugin does not have an open-source license, it is not clear whether others are permitted to redistribute its modifications. https://choosealicense.com/no-permission/
