### ISSUE TITLE
BedWars by Fludixx

### ISSUE THREAD

**Issue by ghost** [poggit-orphanage/office#38]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name
BedWars

#### Link to GitHub repo

https://github.com/Fludixx/Bedwars

#### Link to PocketMine Forums release

.....

#### Was it released before mid-2014?
No
#### Does the plugin work in the latest PocketMine version?

It’s currently running on 3.0.0

#### Does the plugin depend on other plugins? Are they released on Poggit?
No I don’t think so
#### Are the main authors still active?

They have active for 21 days

#### Are there any forks that have updated the plugin to the latest PocketMine version?
No

**Comment by SOF3** [comment]
21 days old? That's not an *old* plugin.
