### ISSUE TITLE
Request to add a plugin on poggit release 

### ISSUE THREAD

**Issue by Waater** [poggit-orphanage/office#44]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name
 HardCoreFactionsPE

#### Link to GitHub repo
 https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjkgoqevozkAhVNRa0KHYndAlYQFjAAegQIAxAB&url=https%3A%2F%2Fgithub.com%2FOGFris%2FHardCoreFactionsPE&usg=AOvVaw2ASq8KbqejqBrMqUH_d1yn 

#### Was it released before mid-2014?
 No, it was released after 2014

#### Does the plugin work in the latest PocketMine version?

 Yes

#### Does the plugin depend on other plugins? Are they released on Poggit?
 No

#### Are the main authors still active?
 Not really Twitter for main author is @FrisXYZ

#### Are there any forks that have updated the plugin to the latest PocketMine version?
 yes, there are forks that have updated the plugin around 6 months ago

**Comment by Waater** [comment]
I tried my best answering these questions since I’m not a developer or programmer, I just wanted the plugin to be released on poggit

**Comment by ghost** [comment]
edit: https://github.com/OGFris/HardCoreFactionsPE

**Comment by SOF3** [comment]
As the linked repository does not have a license, we are not permitted to fork and redistribute modifications. Rejected.
