### ISSUE TITLE
BlockCMD

### ISSUE THREAD

**Issue by errox404** [poggit-orphanage/office#45]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

BlockCMD

#### Link to GitHub repo

https://github.com/kenygamer/BlockCMD

#### Was it released before mid-2014?

Nope

#### Does the plugin work in the latest PocketMine version?

No it doesn't work

#### Does the plugin depend on other plugins? Are they released on Poggit?

No 

#### Are the main authors still active?

kenygamer

#### Are there any forks that have updated the plugin to the latest PocketMine version?

No

**Comment by SOF3** [comment]
This plugin is pointless. Use permissions.

**Comment by ghost** [comment]
the plugin works fine on pmmp 3.9.1

**Comment by MrPandaz** [comment]
API changes happen buddy
