### ISSUE TITLE
TeaSpoon

### ISSUE THREAD

**Issue by jaylac2000** [poggit-orphanage/office#46]
please fix teaspoon it'sis no longer being managed  had issuesissue with crafting

**Comment by SOF3** [comment]
Teaspoon is the source of many bugs, and we're not dedicated enough to maintain something this large, nor do I think anyone can reasonably do so.

**Comment by SOF3** [comment]
Teaspoon is explicitly against Poggit's plugin submission rule A2: plugins must serve a specific purpose; not a bunch of stuff mixed together.
