### ISSUE TITLE
JoinCommands

### ISSUE THREAD

**Issue by Distemi** [poggit-orphanage/office#51]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name
JoinCommands

#### Link to GitHub repo
https://github.com/Distemi/JoinCommands

#### Link to PocketMine Forums release
I searched and found similar projects, but they are old and so I decided to make a new one from scratch. (http://forums.pocketmine.net/plugins/joincommands.872/)

#### Was it released before mid-2014?
no

#### Does the plugin work in the latest PocketMine version?
latest stable PocketMine-MP version.
API version: 3.11.7

#### Does the plugin depend on other plugins? Are they released on Poggit?
no

#### Are the main authors still active?
I'm, Discord: Distemi#3091

#### Are there any forks that have updated the plugin to the latest PocketMine version?
As far as I know, no, but I want to keep making more plugins myself and keep developing this one too.

**Comment by SOF3** [comment]
...
https://poggit.pmmp.io/plugins?term=join

**Comment by SOF3** [comment]
Also you don't need to send to poggit orphanage if it's your own creation.
