### ISSUE TITLE
Pmmp-Request

### ISSUE THREAD

**Issue by ghost** [poggit-orphanage/office#53]
Sorry, This was a test for my new github.
Thank you,
Dav S.

**Comment by jasonw4331** [comment]
EssentialsPE is maintained in development builds. It will not be released because it is considered a “core”.

**Comment by ghost** [comment]
I did not send a request, please remove my request and I will handle the restThank you,David S.  Sent from Mail for Windows 10 From: jasonwynn10Sent: Wednesday, July 15, 2020 1:30 PMTo: poggit-orphanage/officeCc: sd5617; AuthorSubject: Re: [poggit-orphanage/office] Pmmp-Request (#53) EssentialsPE is maintained in development builds. It will not be released because it is considered a “core”.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
