### ISSUE TITLE
Nickname

### ISSUE THREAD

**Issue by KadTheHunter** [poggit-orphanage/office#54]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name
Nickname

#### Link to GitHub repo
https://github.com/KadTheHunter/Nickname

#### Link to PocketMine Forums release
None

#### Was it released before mid-2014?
No

#### Does the plugin work in the latest PocketMine version?
Yes

#### Does the plugin depend on other plugins? Are they released on Poggit?
[PureChat](https://github.com/poggit-orphanage/PureChat/tree/d626b01bb1721ea6f53dc38cd1d62453306e879f/), and yes it is on Poggit.

#### Are the main authors still active?
AryToNeX originally wrote this in 2016 (as seen in the config), but I can not find the original repo.
ElektroPrinz uploaded a copy to GitHub in February 2019, but has since deleted it. 
I forked ElektroPrinz's copy in May 2019, and have since fixed the issues with it.

#### Are there any forks that have updated the plugin to the latest PocketMine version?
https://github.com/KadTheHunter/Nickname

**Comment by ghost** [comment]
DAMN! I'm not sure if I'm allowed to comment... but sooo nany nested 'if' and 'else' statements -.-
Use '||' instead of nested-if statements unless necessary.
Instead of using 'else' statements, use elseif.

**Comment by KadTheHunter** [comment]
> DAMN! I'm not sure if I'm allowed to comment... but sooo nany nested 'if' and 'else' statements -.-
> Use '||' instead of nested-if statements unless necessary.
> Instead of using 'else' statements, use elseif.

Thank you for the feedback, and I think it's fine to comment here given the nature of it, however, please note what I said above:
`AryToNeX originally wrote this in 2016 (as seen in the config), but I can not find the original repo.
ElektroPrinz uploaded a copy to GitHub in February 2019, but has since deleted it.
I forked ElektroPrinz's copy in May 2019, and have since fixed the issues with it.`

I simply fixed the issues with it, I have no intention of rewriting the entire plugin unless poggit requires it. Maybe one day in the future I will, but seeing as it works fine now, I probably won't.

**Comment by ghost** [comment]
I'll fork it soon and update it.
