### ISSUE TITLE
KnockbackFFA

### ISSUE THREAD

**Issue by lightyisreal** [poggit-orphanage/office#57]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

KnockbackFFA

#### Link to GitHub repo

No

#### Link to PocketMine Forums release

No

#### Was it released before mid-2014?

No

#### Does the plugin work in the latest PocketMine version?

Yes

#### Does the plugin depend on other plugins? Are they released on Poggit?

No

#### Are the main authors still active?

No

#### Are there any forks that have updated the plugin to the latest PocketMine version?

I didn't really forked the repo, because it doesn't exist anymore, but I recreated the plugin to make it work better, I still hope that I can make any changes to the repo after you submit it on Poggit so I can mantain it.
https://github.com/AetherPlace/KnockbackFFA

**Comment by lightyisreal** [comment]
So, how's going on?

**Comment by SOF3** [comment]
The way poggit orphanage works is that *any* person (not necessarily admins of poggit orphanage) can adopt an old plugin to maintain. This will be accepted if someone is willing to pick this up.

**Comment by lightyisreal** [comment]
I'm willing to pick the plugin and update it, because I put a lot of effort on updating it.

**Comment by SOF3** [comment]
who was the *original* author? I can't find anyone else on github using this.

**Comment by SOF3** [comment]
since you rewrote the whole plugin yourself, this is not considered an orphan. Please submit the plugin under your own name. Orphans refer to unmaintained source code, not unmaintained ideas. There is no such thing as "copying a plugin idea" in poggit's rules.

**Comment by lightyisreal** [comment]
> since you rewrote the whole plugin yourself, this is not considered an orphan. Please submit the plugin under your own name. Orphans refer to unmaintained source code, not unmaintained ideas. There is no such thing as "copying a plugin idea" in poggit's rules.

When I tried to submit my plugin, someone called jasonwynn10 didn't release the plugin because of "Only submit your own plugins" and I don't even know who was the original author so, why don't you submit my plugin as main owner?
