### ISSUE TITLE
ItemCase update release request

### ISSUE THREAD

**Issue by vojtech-stehlik** [poggit-orphanage/office#62]
I have submitted pull request for ItemCase plugin (it is outdated, plugin does not work with latest api without the pull request)

- Link to poggit release: https://poggit.pmmp.io/p/itemcase
- Part of the plugin which is outdated: https://github.com/poggit-orphanage/ItemCase/blob/master/src/aliuly/itemcasepe/Main.php#L165 (Packet requests itemstackwraper instead of Item)
- Pull request: https://github.com/poggit-orphanage/ItemCase/pull/8

**Comment by SOF3** [comment]
no need to cross reference it here if you have already submitted the PR
