### ISSUE TITLE
VoteReward

### ISSUE THREAD

**Issue by ErikPDev** [poggit-orphanage/office#63]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

VoteReward

#### Link to GitHub repo

https://github.com/poggit-orphanage/VoteReward

#### Link to PocketMine Forums release

https://poggit.pmmp.io/p/VoteReward

#### Was it released before mid-2014?

Nope.

#### Does the plugin work in the latest PocketMine version?

Yes.

#### Does the plugin depend on other plugins? Are they released on Poggit?

The plugin doesn't depend on any projects.

#### Are the main authors still active?

The authors aren't active.

#### Are there any forks that have updated the plugin to the latest PocketMine version?

https://github.com/ErikPDev/VoteReward

**Comment by SOF3** [comment]
Office is for new plugins, not for existing plugins.

Please send pull requests to the repo directly if it is already on orphanage.
