### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by KygekDev** [poggit-orphanage/office#64]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

Functions

#### Link to GitHub repo

https://github.com/BoxOfDevs/Functions

#### Link to PocketMine Forums release

The plugin isn't old enough that it has been released on PocketMine Forums.
https://poggit.pmmp.io/p/Functions

#### Was it released before mid-2014?

No.

#### Does the plugin work in the latest PocketMine version?

Latest commit on GitHub repo: Yes. (Already supports API 3.0.0 as of in `plugin.yml`)
Latest release on Poggit: No.

#### Does the plugin depend on other plugins? Are they released on Poggit?

No.

#### Are the main authors still active?

Yes, but the repository itself has been archived.

#### Are there any forks that have updated the plugin to the latest PocketMine version?

No, but latest commit on orginal GitHub repository already supports latest PocketMine-MP version.

**Comment by SOF3** [comment]
Is it necessary to update Functions when we have Mineflow?

**Comment by reyyan987** [comment]
Yes pmmp should have more plugins of one kind to select from

**Comment by SOF3** [comment]
But it's not meaningful to intentionally create multiple plugins just so that you can select.

**Comment by SOF3** [comment]
If someone created something that can induce competition, sure, we're fine with letting users choose.

But if we just create another plugin for its own sake, it is a waste of time and manpower.
