### ISSUE TITLE
Request to add a plugin to poggit

### ISSUE THREAD

**Issue by achedon12** [poggit-orphanage/office#65]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

CustomBuyRank

#### Link to GitHub repo
https://github.com/leoderoin/CustomBuyRankUI

#### Was it released before mid-2014?
No

#### Does the plugin work in the latest PocketMine version?
Latest commit on GitHub repo: Yes. (Already supports API 3.0.0 as of in plugin.yml)
Latest release on Poggit: No.

#### Does the plugin depend on other plugins? Are they released on Poggit?
Yes
PurePerms and EconomyAPI

#### Are the main authors still active?
yes

#### Are there any forks that have updated the plugin to the latest PocketMine version?
No, but latest commit on orginal GitHub repository already supports latest PocketMine-MP version.

**Comment by SOF3** [comment]
Why request it on poggit-orphanage when main authors are still active?

**Comment by achedon12** [comment]
> Why request it on poggit-orphanage when main authors are still active?

it is because on the plugin that I put on poggit, it is written "submit"

**Comment by SOF3** [comment]
Then wait for it to be submitted. Orphanage is for orphans.
