### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Kylan1940** [poggit-orphanage/office#66]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name
My plugin (OnlineUI and GamemodeUI)

#### Link to GitHub repo
https://github.com/Kylan1940/GamemodeUI (GamemodeUI) 
https://github.com/Kylan1940/OnlineUI (OnlineUI)

#### Was it released before mid-2014?
No

#### Does the plugin work in the latest PocketMine version?
Yes

#### Does the plugin depend on other plugins? Are they released on Poggit?
Yes, FormAPI

#### Are the main authors still active?
Yes, me :D

#### Are there any forks that have updated the plugin to the latest PocketMine version?
No

#### Detail
```500 Internal Server Error
A server internal error occurred. Please use this request ID for reference if you need support: f4b8-67ef445731b804b8-AMS

Logging out may solve the problem.

**Comment by SOF3** [comment]
Uh... why are you reporting a poggit bug on orphanage?

**Comment by SOF3** [comment]
For your information, FormAPI is no longer allowed as a plugin dependency (use virions please). Using it in your `depend` in plugin.yml may lead to 500ISE on poggit because FormAPI has since been rejected
