### ISSUE TITLE
FormAPI

### ISSUE THREAD

**Issue by tpguy825** [poggit-orphanage/office#69]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

FormAPI

#### Link to GitHub repo

https://github.com/jojoe77777/FormAPI

#### Was it released before mid-2014?

No

#### Does the plugin work in the latest PocketMine version?

No

#### Does the plugin depend on other plugins? Are they released on Poggit?

No

#### Are the main authors still active?

No

#### Are there any forks that have updated the plugin to the latest PocketMine version?

https://github.com/tpguy825/FormAPI

**Comment by SOF3** [comment]
FormAPI should no longer be used as a plugin. Please use its virion form instead.
