### ISSUE TITLE
SlowTransfer and FastTransfer

### ISSUE THREAD

**Issue by zm-ibrahim** [poggit-orphanage/office#7]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name
FastTransfer & SlowTransfer

#### Link to GitHub repo
Fasttransfer : https://github.com/shoghicp/FastTransfer
SlowTransfer : https://github.com/Falkirks/SlowTransfer

#### Link to PocketMine Forums release
FastTransfer : http://forums.pocketmine.net/plugins/fasttransfer.1142/

#### Is it in the post-Alpha_1.4 format?
I dont Know

#### Does the plugin work in the latest PocketMine version?
No

#### Does the plugin depend on other plugins? Are they released on Poggit?
For SlowTransfer , Yes, FastTransfer. 
No, they not

#### Are the main authors still active?
Maybe.. (?)

**Comment by SOF3** [comment]
About FastTransfer: It is no longer necessary because there is the /transferserver command.
About SlowTransfer: It is by @Falkirks, an active developer, and Poggit Orphanage prefers to avoid updating plugins of active developers before obtaining their prior approval.
