### ISSUE TITLE
FormAPI

### ISSUE THREAD

**Issue by AzliRynz** [poggit-orphanage/office#73]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

FormAPI

#### Link to GitHub repo

https://github.com/NurAzliYT/FormAPI

#### Was it released before mid-2014?

no

#### Does the plugin work in the latest PocketMine version?

Yes

#### Does the plugin depend on other plugins? Are they released on Poggit?

Devtools

#### Are the main authors still active?

NurAzliYT
NurAzli

#### Are there any forks that have updated the plugin to the latest PocketMine version?

5.0.0 - 5.5.0

**Comment by Laith98Dev** [comment]
As the submission rejected reason says, `Libraries must be as virions. They must not be released as individual plugins.`

**Comment by SOF3** [comment]
FormAPI is a library not a plugin.
