### ISSUE TITLE
EasyRegisterLG

### ISSUE THREAD

**Issue by RimVG** [poggit-orphanage/office#76]
## I want this plugin to be approved

This plugin was created to make it easier for players to log in and register

#### Plugin Name
EasyRegisterLG

#### Link to GitHub repo
https://github.com/RimVG/EasyRegisterLG

#### Link to PocketMine Forums release
Don't have it

#### Was it released before mid-2014?
No

#### Does the plugin work in the latest PocketMine version?
Located in API5

#### Does the plugin depend on other plugins? Are they released on Poggit?
I don't have any depend

#### Are the main authors still active?
Yes

#### Are there any forks that have updated the plugin to the latest PocketMine version?
EasyRegisterLG Works on API5

**Comment by jasonw4331** [comment]
This issue system is intended to grant poggit staff approval to transfer ownership of a legacy project which is no longer being maintained onto the poggit orphanage account for continued maintainance. The requested plugin appears to be in active maintenance by the owner and is not meant for a legacy version of PocketMine.

Seeing as how neither requirement has been met, please do not continue spamming posts about this plugin on this issue tracker. This organization has nothing to do with the reviewer team.
