### ISSUE TITLE
Request to add a plugin AntiStuck on Poggit Release

### ISSUE THREAD

**Issue by ErwanScraft** [poggit-orphanage/office#77]
Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

Plugin Name
AntiStuck

Link to GitHub repo
Link: https://github.com/ErwanScraft/AntiStuck

Link to PocketMine Forums release
Nothing

Was it released before mid-2014?
No

Does the plugin work in the latest PocketMine version?
Yes

Does the plugin depend on other plugins? Are they released on Poggit?
No

Are the main authors still active?
Yes and the author myself

Are there any forks that have updated the plugin to the latest PocketMine version?
No

**Comment by jasonw4331** [comment]
This issue system is intended to grant poggit staff approval to transfer ownership of a legacy project which is no longer being maintained onto the poggit orphanage account for continued maintenance. The requested plugin appears to be in active maintenance by the owner and is not meant for any legacy versions of PocketMine-MP.

Seeing as how neither requirement has been met, please do not continue spamming posts about this plugin on this issue tracker. This organization has nothing to do with the reviewer team.
