### ISSUE TITLE
VGRegisterPM

### ISSUE THREAD

**Issue by Tyyuup** [poggit-orphanage/office#78]
This issue tracker is ONLY for request
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

Plugin to make it easier for players to log in
 • /login
 • /register

#### Plugin Name
VGRegisterPM

#### Link to GitHub repo
https://github.com/YunusVG/VGRegisterPM

#### Link to PocketMine Forums release
Nothing

#### Was it released before mid-2014?
No

#### Does the plugin work in the latest PocketMine version?
Yes

#### Does the plugin depend on other plugins? Are they released on Poggit?
Yes

#### Are the main authors still active?
Active

#### Are there any forks that have updated the plugin to the latest PocketMine version?
Yes

**Comment by SOF3** [comment]
this isn't a place to request plugin review

**Comment by jasonw4331** [comment]
This issue system is intended to grant poggit staff approval to transfer ownership of a legacy project which is no longer being maintained onto the poggit orphanage account for continued maintenance. The requested plugin appears to be in active maintenance by the repository owner and is not meant for any legacy versions of PocketMine-MP.

Seeing as how neither requirement has been met, please do not continue spamming posts about this plugin on this issue tracker. This organization has nothing to do with the reviewer team.
