### ISSUE TITLE
AutomaticServerRestart Request

### ISSUE THREAD

**Issue by KurojakiKaoru** [poggit-orphanage/office#9]
## Request to add a plugin on Poggit Release
I am writing to request that an old plugin be added onto Poggit Release. Details are as follows:

#### Plugin Name

ASR

#### Link to GitHub repo

Original:
https://github.com/iJoshuaHD/ASR
My updated version:
https://github.com/LeronDoesGM/AutoServerRestart

#### Link to PocketMine Forums release

http://forums.pocketmine.net/plugins/automatic-server-restarter.903/

#### Is it in the pre-Alpha_1.4 format?

No

#### Does the plugin work in the latest PocketMine version?

The orginal plugin doesn't but mine does.

#### Does the plugin depend on other plugins? Are they released on Poggit?

No

#### Are the main authors still active?

No

**Comment by Awzaw** [comment]
It's a shame you didn't fork the original repo, and I don't think your version is compatible with API 3.0.0-ALPHA6 and Alpha7. Also, correct me if I'm wrong but you haven't added any functionality so this is unlikely to be accepted as your plugin, and more likely to be added to Poggit by poggit-orphanage as a fork of the original repo, to which you could make pull requests if you had forked...

**Comment by KurojakiKaoru** [comment]
I have tested the plugin and it is fully supported for 3.0.0-ALPHA7, I will remove support for 3.0.0-ALPHA6 since pocketmine updated everything for the new api.

**Comment by KurojakiKaoru** [comment]
I also had no knowledge of the process poggit uses if you don't fork the project. @Awzaw

**Comment by SOF3** [comment]
This plugin could be replaced with TimeCommander.
